@echo off
echo Initializing Git repository...
git init
echo Adding files to git...
git add .
echo Committing files...
git commit -m "Initial commit of Kitoko RFM Analysis project"
echo Setting branch to main...
git branch -M main
echo Configuring remote origin...
git remote remove origin 2>nul
git remote add origin https://github.com/hemalsureja/Kitoko-RFM-Analysis.git
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
